# Generated by Django 3.2.16 on 2023-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pending_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
