# Generated by Django 3.2.16 on 2023-03-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='club',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='showing',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Student', 'Student')], default='Adult', max_length=10),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.IntegerField(default=0)),
                ('ticket_count', models.IntegerField(default=0)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UWEFlix.club')),
                ('showing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UWEFlix.showing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UWEFlix.booking'),
        ),
    ]
