# Generated by Django 3.2.16 on 2023-05-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(default='Transaction', max_length=100),
        ),
    ]
