# Generated by Django 4.1.3 on 2023-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_auto_20230328_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='seats_taken',
            field=models.IntegerField(default=0),
        ),
    ]
