# Generated by Django 4.1.3 on 2023-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_userprofile_applied_club_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='applied_club_rep',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
