# Generated by Django 4.1.3 on 2023-05-01 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0003_alter_userprofile_applied_club_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_obj',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
