# Generated by Django 4.1.3 on 2023-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0003_showing_seats_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
