# Generated by Django 3.2.16 on 2023-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_remove_booking_user_booking_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='adult_cost',
            field=models.DecimalField(decimal_places=2, default=13.99, max_digits=4),
        ),
        migrations.AddField(
            model_name='showing',
            name='child_cost',
            field=models.DecimalField(decimal_places=2, default=7.99, max_digits=4),
        ),
        migrations.AddField(
            model_name='showing',
            name='student_cost',
            field=models.DecimalField(decimal_places=2, default=11.99, max_digits=4),
        ),
    ]
