# Generated by Django 4.1.3 on 2023-05-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_alter_userprofile_user_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='has_club_rep',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
