# Generated by Django 3.2.16 on 2023-04-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_auto_20230429_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountStatement',
        ),
    ]
