# Generated by Django 3.2.16 on 2023-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0006_alter_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
