version: '3.8'

services:
  film-manager:
    image: ${APP_NAME}
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    ports:
      - "8080:8080"
    entrypoint: ["./Film_Manager-entrypoint.sh"]
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
