# Generated by Django 4.1.3 on 2023-03-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField(blank=True, default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_number', models.PositiveIntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('landline', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('seat', models.CharField(max_length=3)),
                ('booking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClubRep.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRepProfile',
            fields=[
                ('repID', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('credit', models.PositiveIntegerField()),
                ('clubID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClubRep.club')),
            ],
        ),
    ]
