# Generated by Django 4.1.3 on 2023-03-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CinemaManager', '0001_initial'),
        ('ClubRep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CinemaManager.showing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
