# Generated by Django 3.2.16 on 2023-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRepProfile',
            fields=[
                ('repID', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('credit', models.PositiveIntegerField()),
            ],
        ),
    ]
